Updated deploy script

diff --git a/tasks/deploy b/tasks/deploy
--- a/tasks/deploy
+++ b/tasks/deploy
@@ -1,48 +1,39 @@
-#!/bin/sh
+#!/bin/bash
 
-# Working variables
-REMOTE_USER=$USER
-REMOTE_SERVER=starlightcomic.ddns.net
-REMOTE_PATH=/var/www
-TMP_JEKYLL_BUILD=${HOME}/tmp/html
-PUBLIC_WWW=${REMOTE_USER}@${REMOTE_SERVER}:${REMOTE_PATH}
-
-# Echo welcome message
-echo "Starting up deploy script..."
-echo "Hello, ${REMOTE_USER}.\n"
-
-# Build website
-echo "Building Jekyll site to ${TMP_JEKYLL_BUILD}..."
-jekyll build -d $TMP_JEKYLL_BUILD
-
-# Test if jekyll build was succesfull
-RESULT=$?
-if [ $RESULT -ne 0 ]; then
- # Exit if build failed
- echo "Deployment failed: Jekyll build failed"
- exit 1
+# Check if script is run as root.
+if [[ $EUID -ne 0 ]]; then
+  echo "This script must be run as root."
+  exit 1
 fi
 
-echo "Jekyll build successful.\n"
+JEKYLL_DEST=/var/www/moonlight
 
-# Tell user what will be deployed
-echo "Deploying from: $TMP_JEKYLL_BUILD"
-echo "Deploying to: $REMOTE_PATH"
-echo "\n The next few bits will require sudo.\n"
+echo -e "Building Jekyll site to ${JEKYLL_DEST}..."
+jekyll build -d $JEKYLL_DEST
 
-# Copies the directory to the public server
-echo "\nInitializing connection to SSH server..."
-rsync -av --delete --exclude share --chmod 664 $TMP_JEKYLL_BUILD $PUBLIC_WWW
-echo "Files successfully copied.\n"
+# Test if jekyll build was succesfull
+RESULT_JEKYLL=$?
+if [ $RESULT_JEKYLL -ne 0 ]; then
+  # Exit if build failed
+  echo -e "\nDeployment failed: Jekyll build failed."
+  exit 1
+fi
 
-# Removes the temp directory as we don't need it anymore
-echo "Removing ${TMP_JEKYLL_BUILD}..."
-rm -rf $TMP_JEKYLL_BUILD
+echo -e "\nJekyll build successful."
 
 # Cleans folder permissions
-#echo "Cleaning file & folder permissions in ${REMOTE_PATH}..."
-#sudo chown -R root:remote $REMOTE_PATH
-#sudo chmod -R 775 $REMOTE_PATH
+echo -e "Cleaning file & folder permissions in ${JEKYLL_DEST}...\n"
+chown -R www-data:www-data $JEKYLL_DEST
+chmod -R 775 $JEKYLL_DEST
 
-echo "\nDeploy successful."
+# Test if chown/chmod was succesfull
+RESULT_CHMOD=$?
+if [ $RESULT_CHMOD -ne 0 ]; then
+  # Exit if failed
+  echo -e "\nFailed cleaning permissions in ${JEKYLL_DEST}"
+  echo -e "You might want to manually chmod/chroot at this point."
+  exit 0
+fi
+
+echo -e "Done."
 exit
